apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: school-hub
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: schoolhub
  DB_USER: postgres
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  CORS_ALLOWED_ORIGINS: "http://localhost,http://frontend"
  CELERY_BROKER_URL: "redis://redis:6379/1"
  CELERY_RESULT_BACKEND: "redis://redis:6379/1"
  TIME_ZONE: "UTC"

